package com.backend_core.recruforce2.mongo.repository;

import com.backend_core.recruforce2.mongo.document.ParsedCvDocument;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * MongoDB repository for {@link ParsedCvDocument}.
 * Provides access to the {@code parsed_cvs} collection in MongoDB.
 * <p>
 * Documents are created by the Python AI microservice after CV parsing.
 * Linked to PostgreSQL {@code candidates} table via {@code candidateId}.
 */
@Repository
public interface ParsedCvMongoRepository extends MongoRepository<ParsedCvDocument, String> {

  /** Finds the parsed CV document for a specific PostgreSQL candidate ID */
  Optional<ParsedCvDocument> findByCandidateId(Long candidateId);

  /** Checks if a parsed CV exists for a candidate */
  boolean existsByCandidateId(Long candidateId);

  /** Finds all parsed CVs generated by a specific AI model version */
  List<ParsedCvDocument> findByModelVersion(String modelVersion);

  /** Finds parsed CVs by original filename */
  List<ParsedCvDocument> findByOriginalFilename(String originalFilename);

  /** Finds parsed CVs with a parsing confidence above a threshold */
  @Query("{ 'parsing_confidence': { $gte: ?0 } }")
  List<ParsedCvDocument> findByParsingConfidenceGreaterThanEqual(Double threshold);

  /** Finds parsed CVs associated with a specific N8N workflow execution */
  List<ParsedCvDocument> findByWorkflowId(String workflowId);

  /** Deletes the parsed CV document for a specific candidate (GDPR erasure) */
  void deleteByCandidateId(Long candidateId);
}
