package com.backend_core.recruforce2.repository;

import com.backend_core.recruforce2.domain.entities.Prediction;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * JPA repository for {@link Prediction} entity.
 * Provides access to the {@code predictions} table in PostgreSQL.
 */
@Repository
public interface PredictionResultRepository extends JpaRepository<Prediction, Long> {

  /** Finds the latest prediction for a candidate/job offer pair */
  Optional<Prediction> findTopByCandidateIdAndJobOfferIdOrderByCalculatedAtDesc(
    Long candidateId, Long jobOfferId);

  /** Finds all predictions for a specific candidate */
  List<Prediction> findByCandidateIdOrderByCalculatedAtDesc(Long candidateId);

  /** Finds all predictions for a specific job offer (paginated) */
  Page<Prediction> findByJobOfferIdOrderByMatchingScoreDesc(Long jobOfferId, Pageable pageable);

  /** Finds top predictions for a job offer above a score threshold */
  @Query("SELECT p FROM Prediction p WHERE " +
    "p.jobOffer.id = :jobOfferId AND " +
    "p.matchingScore >= :threshold " +
    "ORDER BY p.matchingScore DESC")
  List<Prediction> findTopByJobOffer(@Param("jobOfferId") Long jobOfferId,
                                     @Param("threshold") Double threshold);

  /** Finds predictions generated by a specific ML model version */
  List<Prediction> findByModelVersion(String modelVersion);

  /** Calculates the average matching score for a job offer */
  @Query("SELECT AVG(p.matchingScore) FROM Prediction p WHERE p.jobOffer.id = :jobOfferId")
  Double averageMatchingScoreByJobOffer(@Param("jobOfferId") Long jobOfferId);

  /** Finds predictions for a specific ML model */
  Page<Prediction> findByModelId(Long modelId, Pageable pageable);

  /** Counts predictions generated by a specific ML model */
  long countByModelId(Long modelId);
}
